export {
  DEFAULT_BASE_URL,
  DEFAULT_CONEXUS_API_URL,
  DEFAULT_CONEXUS_AUDIENCE,
  DEFAULT_CONEXUS_BASE_URL,
  DEFAULT_CONEXUS_PUBLICATION_SLUG,
  DEFAULT_MODEL,
  MANAGED_DEFAULT_MODEL,
  createAiClient as createClient,
  getAiModel as getModel,
} from '@techunter/core';
